### ISSUE TITLE
[python] Omitting log code swallows format errors

### ISSUE THREAD

**Issue by joerunde** [IBM/alchemy-logging#163]
## Platform

- [x] `python`
  * Interpreter version: 3.9.6
  * Library version: 1.0.4
- [ ] `typescript`
  * `node` version:
  * Package version:
- [ ] `go`
  * Operating system:
  * Compiler version:
  * Package version:
- [ ] `c++`
  * Operating system:
  * Compiler version:
  * Library version:
  * Project build system:

## Sample Code

```
LOGGER.info("<COM10001100I>", "HELLO %s", "WORLD", "FOO")
```
will correctly throw
`TypeError: not all arguments converted during string formatting`

But omitting the log code
```
LOGGER.info("HELLO %s", "WORLD", "FOO")
```
will swallow the error
```
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib64/python3.9/logging/__init__.py", line 1083, in emit
    msg = self.format(record)
  File "/usr/lib64/python3.9/logging/__init__.py", line 927, in format
    return fmt.format(record)
  File "/usr/local/lib/python3.9/site-packages/alog/alog.py", line 235, in format
    record.message = record.getMessage()
  File "/usr/lib64/python3.9/logging/__init__.py", line 367, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/lib64/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib64/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/app/watson_runtime/f.py", line 14, in <module>
    LOGGER.info("HELLO %s", "WORLD", "FOO")
  File "/usr/local/lib/python3.9/site-packages/alog/alog.py", line 369, in <lambda>
    _log_with_code_method_override(self, value, arg_one, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/alog/alog.py", line 363, in _log_with_code_method_override
    self.log(value, arg_one, *args, **g_log_extra_kwargs, **kwargs)
Message: 'HELLO %s'
Arguments: ('WORLD', 'FOO')
```

## Expected behavior
alog should always raise an error if the wrong number of format args are supplied 

## Observed behavior
What you see happening (error messages, stack traces, etc...)

**Comment by gabe-l-hart** [comment]
Closed with #165
