### ISSUE TITLE
Interaction between alog and uvicorn causes ValueError during API calls

### ISSUE THREAD

**Issue by DaopingWang** [IBM/alchemy-logging#183]
## Describe the bug

Hi there, I’m writing a FastAPI + uvicorn Python backend to serve models with the `watson_nlp` library and encountered an issue with `alchemy-logging`.

As long as I do `import watson_nlp` or `import alog`, a `ValueError: not enough values to unpack (expected 5, got 0)` will be raised by the uvicorn logger whenever an API is called. The error is about uvicorn not able to handle the log record object generated during the API call. The error log and the Python code are down below.

However, if I do an explicit `pip install alog` ( it installs `alog-1.2.7` ), the problem is gone… My guess is that the current version of `alchemy-logging` is maybe carrying some outdated version of `alog` with it?

To sum up the behavior:

- `import watson_nlp` causes the `ValueError` in the uvicorn logger, original problem.
- Changing `import watson_nlp` to `import alog`, and the issue persists.
- `pip install alog` installs `alog-1.2.7` and the issue is gone.

## Platform

- [ ] `python`
  * Interpreter version: 3.9.12
  * Library version: 1.0.5

## Sample Code

```python
import uvicorn
from fastapi import FastAPI
from fastapi import APIRouter
# import watson_nlp
import alog
​
router = APIRouter(
    prefix="/watson-nlp",
)
​
​
@router.get("/healthz")
async def health():
    return {"isHealthy": True}
​
​
app = FastAPI(
    docs_url="/watson-nlp/docs",
    openapi_url="/watson-nlp/v1/openapi.json")
​
​
app.include_router(router)
​
if __name__ == "__main__":
    uvicorn.run("playground:app",
                host="0.0.0.0",
                port=4000,
                reload=True)
```

## Expected behavior
No "interference" between alog and the uvicorn logger

## Observed behavior

```
INFO:     Started server process [25984]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:4000 (Press CTRL+C to quit)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/logging/__init__.py", line 1083, in emit
    msg = self.format(record)
  File "/usr/local/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/logging/__init__.py", line 927, in format
    return fmt.format(record)
  File "/usr/local/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/logging/__init__.py", line 666, in format
    s = self.formatMessage(record)
  File "/Users/daopingwang/workspace/lka-rlp-hasso-watson-nlp-sidecar/.venv/lib/python3.9/site-packages/uvicorn/logging.py", line 99, in formatMessage
    (
ValueError: not enough values to unpack (expected 5, got 0)
Call stack:
  File "/usr/local/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/daopingwang/workspace/lka-rlp-hasso-watson-nlp-sidecar/.venv/lib/python3.9/site-packages/uvicorn/__main__.py", line 4, in <module>
    uvicorn.main()
  File "/Users/daopingwang/workspace/lka-rlp-hasso-watson-nlp-sidecar/.venv/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/daopingwang/workspace/lka-rlp-hasso-watson-nlp-sidecar/.venv/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/daopingwang/workspace/lka-rlp-hasso-watson-nlp-sidecar/.venv/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/daopingwang/workspace/lka-rlp-hasso-watson-nlp-sidecar/.venv/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/daopingwang/workspace/lka-rlp-hasso-watson-nlp-sidecar/.venv/lib/python3.9/site-packages/uvicorn/main.py", line 437, in main
    run(app, **kwargs)
  File "/Users/daopingwang/workspace/lka-rlp-hasso-watson-nlp-sidecar/.venv/lib/python3.9/site-packages/uvicorn/main.py", line 463, in run
    server.run()
  File "/Users/daopingwang/workspace/lka-rlp-hasso-watson-nlp-sidecar/.venv/lib/python3.9/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/local/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 634, in run_until_complete
    self.run_forever()
  File "/usr/local/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 601, in run_forever
    self._run_once()
  File "/usr/local/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 1905, in _run_once
    handle._run()
  File "/usr/local/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/Users/daopingwang/workspace/lka-rlp-hasso-watson-nlp-sidecar/.venv/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 366, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/Users/daopingwang/workspace/lka-rlp-hasso-watson-nlp-sidecar/.venv/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/Users/daopingwang/workspace/lka-rlp-hasso-watson-nlp-sidecar/.venv/lib/python3.9/site-packages/fastapi/applications.py", line 269, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/daopingwang/workspace/lka-rlp-hasso-watson-nlp-sidecar/.venv/lib/python3.9/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/daopingwang/workspace/lka-rlp-hasso-watson-nlp-sidecar/.venv/lib/python3.9/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/Users/daopingwang/workspace/lka-rlp-hasso-watson-nlp-sidecar/.venv/lib/python3.9/site-packages/starlette/exceptions.py", line 82, in __call__
    await self.app(scope, receive, sender)
  File "/Users/daopingwang/workspace/lka-rlp-hasso-watson-nlp-sidecar/.venv/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/Users/daopingwang/workspace/lka-rlp-hasso-watson-nlp-sidecar/.venv/lib/python3.9/site-packages/starlette/routing.py", line 670, in __call__
    await route.handle(scope, receive, send)
  File "/Users/daopingwang/workspace/lka-rlp-hasso-watson-nlp-sidecar/.venv/lib/python3.9/site-packages/starlette/routing.py", line 266, in handle
    await self.app(scope, receive, send)
  File "/Users/daopingwang/workspace/lka-rlp-hasso-watson-nlp-sidecar/.venv/lib/python3.9/site-packages/starlette/routing.py", line 68, in app
    await response(scope, receive, send)
  File "/Users/daopingwang/workspace/lka-rlp-hasso-watson-nlp-sidecar/.venv/lib/python3.9/site-packages/starlette/responses.py", line 155, in __call__
    await send(
  File "/Users/daopingwang/workspace/lka-rlp-hasso-watson-nlp-sidecar/.venv/lib/python3.9/site-packages/starlette/exceptions.py", line 79, in sender
    await send(message)
  File "/Users/daopingwang/workspace/lka-rlp-hasso-watson-nlp-sidecar/.venv/lib/python3.9/site-packages/starlette/middleware/errors.py", line 159, in _send
    await send(message)
  File "/Users/daopingwang/workspace/lka-rlp-hasso-watson-nlp-sidecar/.venv/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 431, in send
    self.access_logger.info(
  File "/Users/daopingwang/workspace/lka-rlp-hasso-watson-nlp-sidecar/.venv/lib/python3.9/site-packages/alog/alog.py", line 373, in <lambda>
    _log_with_code_method_override(self, value, arg_one, *args, **kwargs)
  File "/Users/daopingwang/workspace/lka-rlp-hasso-watson-nlp-sidecar/.venv/lib/python3.9/site-packages/alog/alog.py", line 367, in _log_with_code_method_override
    self.log(value, message, **g_log_extra_kwargs, **kwargs)
Message: '127.0.0.1:52642 - "GET /watson-nlp/docs HTTP/1.1" 200'
Arguments: ()
```

**Comment by gabe-l-hart** [comment]
Ok, I think I've found a lead. [this line](https://github.com/encode/uvicorn/blob/0.17.6/uvicorn/logging.py#L97) in `uvicorn` seems to be making a strong assumption about the content of the arguments given to a logging function, and this is in conflict with [an assumption made in `alog`](https://github.com/IBM/alchemy-logging/blob/main/src/python/alog/alog.py#L362) that it's ok to pre-interpolate the the string.

**Comment by gabe-l-hart** [comment]
I needed to tweak the repro case a bit to see the exception come out, but this does the trick:

```py
import uvicorn
from fastapi import FastAPI
from fastapi import APIRouter
import requests
import threading
import time
import alog

router = APIRouter(
    prefix="/watson-nlp",
)


@router.get("/healthz")
async def health():
    return {"isHealthy": True}


app = FastAPI(
    docs_url="/watson-nlp/docs",
    openapi_url="/watson-nlp/v1/openapi.json")


app.include_router(router)

if __name__ == "__main__":
    th = threading.Thread(
        target=uvicorn.run,
        args=(app,),
        kwargs={"host": "0.0.0.0", "port": 4000},
    )
    th.start()
    time.sleep(2)
    requests.get("https://localhost:4000")

    th.join()
```

This is using the following package versions:

```
anyio==3.6.1
asgiref==3.5.2
attrs==21.4.0
certifi==2022.5.18.1
charset-normalizer==2.0.12
click==8.1.3
coverage==6.4.1
fastapi==0.78.0
h11==0.13.0
idna==3.3
iniconfig==1.1.1
packaging==21.3
pluggy==1.0.0
py==1.11.0
pydantic==1.9.1
pyparsing==3.0.9
pytest==7.0.1
pytest-cov==3.0.0
requests==2.27.1
sniffio==1.2.0
starlette==0.19.1
tomli==2.0.1
typing_extensions==4.2.0
urllib3==1.26.9
uvicorn==0.17.6
```

**Comment by gabe-l-hart** [comment]
Minimal repro without needing to boot the server:

```py
import logging
import uvicorn
logging.config.dictConfig(uvicorn.config.LOGGING_CONFIG)
logger = logging.getLogger("uvicorn.access")

# This works
logger.info('%s - "%s %s HTTP/%s" %d', "1.2.3.4", "GET", "/foo/bar", "2.0", 200)

# This fails
import alog
logger.info('%s - "%s %s HTTP/%s" %d', "1.2.3.4", "GET", "/foo/bar", "2.0", 200)
```
